Repository web-standards-ru/nouvelle, pull requests merged in 2019-12, with the labels that each got.

#150 Делает компактную шапку для внутренних страниц
  src/includes/header.njk
  src/layouts/page.njk
  src/styles/blocks/header.css
  src/styles/blocks/logo.css
  src/styles/blocks/navigation.css
  src/styles/blocks/page.css
Labels: 11ty, Вёрстка, Для запуска

#151 Корректирует статью Инклюзивные компоненты: список дел
  src/articles/a-todo-list/index.md
Labels: Контент

#124 Делает наведение по дизайну
  src/styles/blocks/content.css
  src/styles/blocks/footer.css
  src/styles/blocks/logo.css
  src/styles/blocks/navigation.css
  src/styles/styles.css
Labels: В работе, Вёрстка, Дизайн

#153 Добавляет правило запрещающее хаотичную нумерацию списков в markdown
  package-lock.json
  package.json
  src/articles/a11y-and-law/index.md
  src/articles/es-modules-cartoon-dive/index.md
  src/articles/menu-buttons/index.md
  src/articles/top-themes-and-frameworks/index.md
Labels: Окружение

#152 Добавляет альты в статью Доступность и закон
  src/articles/a11y-and-law/index.md
Labels: Данные

#155 Делает наведение по дизайну
  src/layouts/page.njk
  src/scripts/navigation.js
  src/styles/blocks/authors.css
  src/styles/blocks/content.css
  src/styles/blocks/footer.css
  src/styles/blocks/informer.css
  src/styles/blocks/logo.css
  src/styles/blocks/navigation.css
  src/styles/styles.css
Labels: JS, Вёрстка, Для запуска

#157 Добавляет определение разметки в статью
  src/articles/boring-bits-of-css/index.md
Labels: Контент
