Repository web-standards-ru/nouvelle, pull requests merged in 2019-11, with the labels that each got.

#101 Адаптирует header
  src/includes/header.njk
  src/layouts/page.njk
  src/scripts/navigation.js
  src/styles/blocks/archive.css
  src/styles/blocks/header.css
  src/styles/blocks/informer.css
  src/styles/blocks/logo.css
  src/styles/blocks/main.css
  src/styles/blocks/navigation.css
  src/styles/blocks/page.css
  src/styles/blocks/preview.css
Labels: 11ty, В работе, Вёрстка

#122 Добавляет clip-path для картинок авторов
  src/images/author--placeholder.jpg
  src/images/blob.svg
  src/layouts/page.njk
  src/pages/index.njk
  src/styles/blocks/preview.css
  src/styles/blocks/visually-hidden.css
  src/styles/styles.css
Labels: В работе, Вёрстка, Дизайн

#121 Доделывает логотип header
  src/includes/header.njk
  src/layouts/page.njk
  src/styles/blocks/logo.css
Labels: В работе, Вёрстка, Для запуска

#129 Добавляет запрет пустой строки между свойствами
  package.json
Labels: Окружение

#136 Объединяет иконку и ссылку "Поддержать проект"
  src/styles/blocks/navigation.css
Labels: Вёрстка, Для запуска

#138 Добавляет правило в stylelint для свойства line-height
  package.json
Labels: Окружение

#142 Исправляет семантическую структуру страниц
  src/layouts/page.njk
Labels: В работе, Вёрстка, Для запуска
